const MS_PER_DAY = 24 * 60 * 60 * 1000

function at(daysAgo, hour, minute = 0) {
  const date = new Date(Date.now() - daysAgo * MS_PER_DAY)
  date.setHours(hour, minute, 0, 0)
  return date.toISOString()
}

export const dashboardAccounts = [
  {
    id: 'funded-alpha',
    name: 'Funded Alpha',
    broker: 'FTMO MetaTrader',
    currency: 'USD',
    startingBalance: 50000,
    equity: 54280
  },
  {
    id: 'swing-vault',
    name: 'Swing Vault',
    broker: 'Interactive Brokers',
    currency: 'USD',
    startingBalance: 25000,
    equity: 26640
  },
  {
    id: 'crypto-edge',
    name: 'Crypto Edge',
    broker: 'Binance Futures',
    currency: 'USDT',
    startingBalance: 18000,
    equity: 19310
  }
]

const rawTrades = [
  {
    id: 'T-1042',
    accountId: 'funded-alpha',
    symbol: 'XAUUSD',
    assetType: 'forex',
    side: 'long',
    entryPrice: 2356.2,
    exitPrice: 2368.4,
    stopLoss: 2349.8,
    takeProfit: 2374.5,
    volume: 38,
    commission: 12,
    fee: 2,
    session: 'London',
    strategyTag: 'Liquidity Sweep',
    emotionTag: 'Calm',
    marketCondition: 'Trend',
    entryTime: at(1, 9, 12),
    exitTime: at(1, 10, 18),
    screenshot: '',
    notes: 'Clean sweep into VWAP reclaim.'
  },
  {
    id: 'T-1041',
    accountId: 'funded-alpha',
    symbol: 'EURUSD',
    assetType: 'forex',
    side: 'short',
    entryPrice: 1.0868,
    exitPrice: 1.0836,
    stopLoss: 1.0886,
    takeProfit: 1.0818,
    volume: 140000,
    commission: 8,
    fee: 1,
    session: 'NewYork',
    strategyTag: 'Break Retest',
    emotionTag: 'Focused',
    marketCondition: 'Range Break',
    entryTime: at(2, 14, 6),
    exitTime: at(2, 15, 22),
    screenshot: '',
    notes: 'Retest held under prior value area.'
  },
  {
    id: 'T-1040',
    accountId: 'crypto-edge',
    symbol: 'BTCUSDT',
    assetType: 'crypto',
    side: 'long',
    entryPrice: 62420,
    exitPrice: 61890,
    stopLoss: 62090,
    takeProfit: 63480,
    volume: 0.72,
    commission: 10,
    fee: 3,
    session: 'Asia',
    strategyTag: 'Opening Drive',
    emotionTag: 'FOMO',
    marketCondition: 'Volatile',
    entryTime: at(3, 7, 36),
    exitTime: at(3, 8, 10),
    screenshot: '',
    notes: 'Entry chased after impulse.'
  },
  {
    id: 'T-1039',
    accountId: 'swing-vault',
    symbol: 'NVDA',
    assetType: 'stocks',
    side: 'long',
    entryPrice: 914.2,
    exitPrice: 928.7,
    stopLoss: 907.8,
    takeProfit: 936.4,
    volume: 42,
    commission: 4,
    fee: 1,
    session: 'NewYork',
    strategyTag: 'Earnings Drift',
    emotionTag: 'Patient',
    marketCondition: 'Trend',
    entryTime: at(4, 13, 45),
    exitTime: at(4, 17, 12),
    screenshot: '',
    notes: 'Held through first pullback.'
  },
  {
    id: 'T-1038',
    accountId: 'funded-alpha',
    symbol: 'GBPJPY',
    assetType: 'forex',
    side: 'short',
    entryPrice: 198.84,
    exitPrice: 199.12,
    stopLoss: 199.03,
    takeProfit: 198.21,
    volume: 24000,
    commission: 7,
    fee: 1,
    session: 'London',
    strategyTag: 'Supply Flip',
    emotionTag: 'Impatient',
    marketCondition: 'Choppy',
    entryTime: at(5, 11, 5),
    exitTime: at(5, 11, 52),
    screenshot: '',
    notes: 'Premature short into compression.'
  },
  {
    id: 'T-1037',
    accountId: 'crypto-edge',
    symbol: 'ETHUSDT',
    assetType: 'crypto',
    side: 'short',
    entryPrice: 3038,
    exitPrice: 2986,
    stopLoss: 3066,
    takeProfit: 2958,
    volume: 8.2,
    commission: 8,
    fee: 2,
    session: 'Asia',
    strategyTag: 'Break Retest',
    emotionTag: 'Focused',
    marketCondition: 'Range Break',
    entryTime: at(6, 6, 20),
    exitTime: at(6, 8, 5),
    screenshot: '',
    notes: 'Weak retest after funding reset.'
  },
  {
    id: 'T-1036',
    accountId: 'funded-alpha',
    symbol: 'NAS100',
    assetType: 'futures',
    side: 'long',
    entryPrice: 18372,
    exitPrice: 18428,
    stopLoss: 18338,
    takeProfit: 18460,
    volume: 4,
    commission: 14,
    fee: 2,
    session: 'NewYork',
    strategyTag: 'Opening Drive',
    emotionTag: 'Calm',
    marketCondition: 'Trend',
    entryTime: at(7, 13, 35),
    exitTime: at(7, 14, 26),
    screenshot: '',
    notes: 'A+ open drive continuation.'
  },
  {
    id: 'T-1035',
    accountId: 'swing-vault',
    symbol: 'AAPL',
    assetType: 'stocks',
    side: 'short',
    entryPrice: 191.4,
    exitPrice: 188.9,
    stopLoss: 193.1,
    takeProfit: 187.4,
    volume: 150,
    commission: 4,
    fee: 1,
    session: 'NewYork',
    strategyTag: 'Supply Flip',
    emotionTag: 'Patient',
    marketCondition: 'Distribution',
    entryTime: at(9, 15, 4),
    exitTime: at(9, 18, 21),
    screenshot: '',
    notes: 'Lower high confirmed under supply.'
  },
  {
    id: 'T-1034',
    accountId: 'funded-alpha',
    symbol: 'USDJPY',
    assetType: 'forex',
    side: 'long',
    entryPrice: 156.12,
    exitPrice: 155.86,
    stopLoss: 155.92,
    takeProfit: 156.58,
    volume: 50000,
    commission: 7,
    fee: 1,
    session: 'Asia',
    strategyTag: 'Liquidity Sweep',
    emotionTag: 'FOMO',
    marketCondition: 'Choppy',
    entryTime: at(10, 4, 50),
    exitTime: at(10, 5, 35),
    screenshot: '',
    notes: 'No confirmation after sweep.'
  },
  {
    id: 'T-1033',
    accountId: 'crypto-edge',
    symbol: 'SOLUSDT',
    assetType: 'crypto',
    side: 'long',
    entryPrice: 142.8,
    exitPrice: 147.9,
    stopLoss: 140.6,
    takeProfit: 149.2,
    volume: 220,
    commission: 7,
    fee: 2,
    session: 'London',
    strategyTag: 'VWAP Reclaim',
    emotionTag: 'Focused',
    marketCondition: 'Trend',
    entryTime: at(12, 10, 10),
    exitTime: at(12, 12, 4),
    screenshot: '',
    notes: 'Momentum held over VWAP.'
  },
  {
    id: 'T-1032',
    accountId: 'funded-alpha',
    symbol: 'GBPUSD',
    assetType: 'forex',
    side: 'short',
    entryPrice: 1.2742,
    exitPrice: 1.2774,
    stopLoss: 1.2762,
    takeProfit: 1.2696,
    volume: 115000,
    commission: 8,
    fee: 1,
    session: 'London',
    strategyTag: 'Break Retest',
    emotionTag: 'Revenge',
    marketCondition: 'Volatile',
    entryTime: at(14, 9, 40),
    exitTime: at(14, 10, 5),
    screenshot: '',
    notes: 'Retest failed, size was too large after prior loss.'
  },
  {
    id: 'T-1031',
    accountId: 'swing-vault',
    symbol: 'MSFT',
    assetType: 'stocks',
    side: 'long',
    entryPrice: 414.8,
    exitPrice: 421.1,
    stopLoss: 411.5,
    takeProfit: 424.6,
    volume: 90,
    commission: 4,
    fee: 1,
    session: 'NewYork',
    strategyTag: 'Earnings Drift',
    emotionTag: 'Calm',
    marketCondition: 'Trend',
    entryTime: at(16, 13, 55),
    exitTime: at(16, 19, 6),
    screenshot: '',
    notes: 'Added after daily range expansion.'
  },
  {
    id: 'T-1030',
    accountId: 'funded-alpha',
    symbol: 'XAUUSD',
    assetType: 'forex',
    side: 'short',
    entryPrice: 2338.6,
    exitPrice: 2327.9,
    stopLoss: 2344.4,
    takeProfit: 2322.6,
    volume: 36,
    commission: 12,
    fee: 2,
    session: 'NewYork',
    strategyTag: 'Liquidity Sweep',
    emotionTag: 'Focused',
    marketCondition: 'Trend',
    entryTime: at(18, 15, 18),
    exitTime: at(18, 16, 30),
    screenshot: '',
    notes: 'NY sweep above highs reversed cleanly.'
  },
  {
    id: 'T-1029',
    accountId: 'crypto-edge',
    symbol: 'BTCUSDT',
    assetType: 'crypto',
    side: 'short',
    entryPrice: 61780,
    exitPrice: 62240,
    stopLoss: 62120,
    takeProfit: 60920,
    volume: 0.62,
    commission: 10,
    fee: 3,
    session: 'Asia',
    strategyTag: 'VWAP Reclaim',
    emotionTag: 'Impatient',
    marketCondition: 'Range',
    entryTime: at(21, 3, 28),
    exitTime: at(21, 4, 8),
    screenshot: '',
    notes: 'Faded reclaim too early.'
  },
  {
    id: 'T-1028',
    accountId: 'funded-alpha',
    symbol: 'EURUSD',
    assetType: 'forex',
    side: 'long',
    entryPrice: 1.0718,
    exitPrice: 1.0769,
    stopLoss: 1.0694,
    takeProfit: 1.0782,
    volume: 120000,
    commission: 8,
    fee: 1,
    session: 'London',
    strategyTag: 'Break Retest',
    emotionTag: 'Calm',
    marketCondition: 'Range Break',
    entryTime: at(25, 8, 46),
    exitTime: at(25, 10, 50),
    screenshot: '',
    notes: 'Breakout from daily compression.'
  },
  {
    id: 'T-1027',
    accountId: 'swing-vault',
    symbol: 'TSLA',
    assetType: 'stocks',
    side: 'short',
    entryPrice: 178.6,
    exitPrice: 181.2,
    stopLoss: 180.2,
    takeProfit: 174.8,
    volume: 110,
    commission: 4,
    fee: 1,
    session: 'NewYork',
    strategyTag: 'Supply Flip',
    emotionTag: 'FOMO',
    marketCondition: 'Volatile',
    entryTime: at(28, 14, 50),
    exitTime: at(28, 15, 18),
    screenshot: '',
    notes: 'Shorted into strength after missed open.'
  },
  {
    id: 'T-1026',
    accountId: 'funded-alpha',
    symbol: 'NAS100',
    assetType: 'futures',
    side: 'long',
    entryPrice: 18120,
    exitPrice: 18172,
    stopLoss: 18092,
    takeProfit: 18192,
    volume: 5,
    commission: 14,
    fee: 2,
    session: 'NewYork',
    strategyTag: 'Opening Drive',
    emotionTag: 'Focused',
    marketCondition: 'Trend',
    entryTime: at(32, 13, 31),
    exitTime: at(32, 14, 16),
    screenshot: '',
    notes: 'Execution aligned with playbook.'
  },
  {
    id: 'T-1025',
    accountId: 'funded-alpha',
    symbol: 'GBPJPY',
    assetType: 'forex',
    side: 'long',
    entryPrice: 197.42,
    exitPrice: 197.16,
    stopLoss: 197.22,
    takeProfit: 197.94,
    volume: 26000,
    commission: 7,
    fee: 1,
    session: 'Asia',
    strategyTag: 'Liquidity Sweep',
    emotionTag: 'Impatient',
    marketCondition: 'Range',
    entryTime: at(36, 5, 14),
    exitTime: at(36, 6, 2),
    screenshot: '',
    notes: 'Took the sweep before higher-low confirmation.'
  }
]

export function calculateTrade(trade) {
  const gross =
    trade.side === 'long'
      ? (trade.exitPrice - trade.entryPrice) * trade.volume
      : (trade.entryPrice - trade.exitPrice) * trade.volume
  const pnl = gross - trade.commission - trade.fee
  const risk = Math.abs(trade.entryPrice - trade.stopLoss) * trade.volume
  const reward = Math.abs(trade.takeProfit - trade.entryPrice) * trade.volume
  const entryMs = new Date(trade.entryTime).getTime()
  const exitMs = new Date(trade.exitTime).getTime()
  return {
    ...trade,
    pnl: Number(pnl.toFixed(2)),
    grossPnl: Number(gross.toFixed(2)),
    risk: Number(risk.toFixed(2)),
    reward: Number(reward.toFixed(2)),
    rMultiple: risk > 0 ? Number((pnl / risk).toFixed(2)) : 0,
    rr: risk > 0 ? Number((reward / risk).toFixed(2)) : 0,
    holdingMinutes: Math.max(1, Math.round((exitMs - entryMs) / 60000))
  }
}

export const mockTrades = rawTrades.map(calculateTrade)
